package com.example.ordermicroservice.model;

import jakarta.persistence.*;
import lombok.Data;

/**
 * The {@code Payment} class represents a payment entity in the order microservice.
 * It is mapped to a database table and contains details such as payment ID, order ID,
 * payment amount, and payment status.
 *
 * <p>This class is annotated with {@code @Entity} to indicate that it is a JPA entity,
 * and {@code @Data} from Lombok to automatically generate getters, setters, toString,
 * equals, and hashCode methods.
 *
 * @author Your Name
 * @version 1.0
 * @since 2023-10-01
 */
@Data
@Entity
public class Payment {

    /**
     * The unique identifier for the payment.
     * This field is automatically generated by the database using an identity column.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The ID of the order associated with this payment.
     * This field links the payment to a specific order.
     */
    private String orderId;

    /**
     * The amount of the payment.
     * This field represents the monetary value of the payment.
     */
    private double amount;

    /**
     * The status of the payment.
     * This field indicates the current state of the payment (e.g., "Pending", "Completed", "Failed").
     */
    private String status;
}